# Generated by Django 4.2.1 on 2023-06-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginpage", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="product", new_name="price",
        ),
        migrations.RemoveField(model_name="product", name="category_id",),
        migrations.RemoveField(model_name="product", name="description",),
        migrations.DeleteModel(name="Category",),
    ]
