# Generated by Django 4.2.1 on 2023-06-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginpage", "0002_rename_product_product_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmazonProduct",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=50)),
                ("rating", models.CharField(max_length=10)),
                ("reviews", models.CharField(max_length=50)),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(name="Product",),
    ]
